let inputWidth;
let inputHeight;
inputWidth=prompt("Enter the width" );
inputHeight=prompt("Enter the height");
let width=parseInt(inputWidth);
let height=parseInt(inputHeight);
document.write("Enter width:<br>");
document.write(width);
document.write("<br>Enter height:<br>");
document.write(height);
let area=height*width;
document.write('<br>The area is '+ area);